<a href="https://colab.research.google.com/github/nadiabaig14/expression_classification/blob/main/expression_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
label_file_path = r"/content/drive/MyDrive/computer_vision_projects/Expression_Classification_With_Facial_Images/data/label/label.lst"
image_folder_path = r"/content/drive/MyDrive/computer_vision_projects/Expression_Classification_With_Facial_Images/Extracted/origin"

In [ ]:
import pandas as pd
df_info = pd.read_csv(label_file_path, sep=' ', header=None)
col_names = "image_name face_id_in_image face_box_top face_box_left face_box_right face_box_bottom face_box_cofidence expression_label".split(' ')
df_info.columns = col_names
df_info

image_name  face_id_in_image  face_box_top  \
0               angry_actor_104.jpg                 0            28   
1               angry_actor_109.jpg                 0            31   
2               angry_actor_120.jpg                 1            53   
3                angry_actor_13.jpg                 0            77   
4               angry_actor_132.jpg                 0            95   
...                             ...               ...           ...   
91788  surprised_expression_546.jpg                 0            70   
91789  surprised_expression_381.jpg                 0            51   
91790  surprised_expression_395.jpg                 0            27   
91791         ecstatic_asian_31.jpg                 0            60   
91792  surprised_expression_394.jpg                 0            47   

       face_box_left  face_box_right  face_box_bottom  face_box_cofidence  \
0                113             226              141             22.9362   
1                157             345              219             50.3056   
2                 53             372              372             13.9434   
3                 51             362              388             85.8104   
4                 31             412              476             82.3948   
...              ...             ...              ...                 ...   
91788             70             351              351             37.7117   
91789             61             117              107             91.6307   
91790             95             258              190             96.2861   
91791            136             184              108             39.9223   
91792             38             152              161             77.7758   

       expression_label  
0                     0  
1                     0  
2                     2  
3                     3  
4                     0  
...                 ...  
91788                 5  
91789                 5  
91790                 5  
91791                 3  
91792                 5  

[91793 rows x 8 columns]

In [ ]:
for ind in df_info.index:
  df_iterate = df_info['image_name'][ind], df_info['face_box_cofidence'][ind]

print(df_iterate)

('surprised_expression_394.jpg', 77.7758)


In [ ]:
df_sel = df_info[df_info.face_box_cofidence > 65]
df_sel

image_name  face_id_in_image  face_box_top  \
3                  angry_actor_13.jpg                 0            77   
4                 angry_actor_132.jpg                 0            95   
5                 angry_actor_137.jpg                 0            93   
9                 angry_actor_150.jpg                 0            56   
11                 angry_actor_16.jpg                 0           158   
...                               ...               ...           ...   
91783            afraid_woman_204.jpg                 0            20   
91787  expressionless_husband_673.jpg                 0            48   
91789    surprised_expression_381.jpg                 0            51   
91790    surprised_expression_395.jpg                 0            27   
91792    surprised_expression_394.jpg                 0            47   

       face_box_left  face_box_right  face_box_bottom  face_box_cofidence  \
3                 51             362              388             85.8104   
4                 31             412              476             82.3948   
5                468             842              467             88.9519   
9                263             376              169             81.8792   
11               249             521              430             66.4535   
...              ...             ...              ...                 ...   
91783             13              93              100             74.5950   
91787            194             388              242             82.2975   
91789             61             117              107             91.6307   
91790             95             258              190             96.2861   
91792             38             152              161             77.7758   

       expression_label  
3                     3  
4                     0  
5                     0  
9                     0  
11                    0  
...                 ...  
91783                 6  
91787                 4  
91789                 5  
91790                 5  
91792                 5  

[27228 rows x 8 columns]

In [ ]:
for i, row in df_sel.iterrows():
  image_name = row['image_name']
  x1 = row['face_box_left']
  x2 = row['face_box_right']
  y1 = row['face_box_top']
  y2 = row['face_box_bottom']
  a = [x1,x2, y1,y2]

print(row)

image_name            surprised_expression_394.jpg
face_id_in_image                                 0
face_box_top                                    47
face_box_left                                   38
face_box_right                                 152
face_box_bottom                                161
face_box_cofidence                         77.7758
expression_label                                 5
Name: 91792, dtype: object


In [ ]:
import os
import cv2
from tqdm import tqdm_gui

X = []
Y = []

image_directory = '/content/drive/MyDrive/computer_vision_projects/Expression_Classification_With_Facial_Images/Extracted/origin'
cropped_directory = '/content/drive/MyDrive/computer_vision_projects/Expression_Classification_With_Facial_Images/cropped'

for i, row in df_sel.sample(1000).iterrows():
    image_name = row['image_name']
    x1 = row['face_box_left']
    x2 = row['face_box_right']
    y1 = row['face_box_top']
    y2 = row['face_box_bottom']
    label = row['expression_label']

    cropped_path = os.path.join(cropped_directory, f"cropped_{image_name}")

    # Read the cropped image
    comb_path = os.path.join(image_directory, image_name)
    cropped_image = cv2.imread(comb_path)

    if cropped_image is not None:
        face = cropped_image[x1:x2, y1:y2]

        # Debugging: Print face shape and cropping coordinates
        print(f"Face shape: {face.shape}, x1={x1}, x2={x2}, y1={y1}, y2={y2}")
    else:
        continue

    if face is not None and not face.size == 0:
        face_resized = cv2.resize(face, (64, 64))
    else:
        continue

    X.append(face_resized)
    Y.append(label)


Face shape: (125, 191, 3), x1=271, x2=462, y1=47, y2=238
Face shape: (0, 57, 3), x1=283, x2=340, y1=33, y2=90
Face shape: (455, 455, 3), x1=151, x2=606, y1=151, y2=606
Face shape: (95, 95, 3), x1=231, x2=326, y1=127, y2=222
Face shape: (47, 47, 3), x1=115, x2=162, y1=59, y2=106
Face shape: (188, 188, 3), x1=172, x2=360, y1=62, y2=250
Face shape: (0, 114, 3), x1=391, x2=505, y1=28, y2=142
Face shape: (230, 230, 3), x1=172, x2=402, y1=95, y2=325
Face shape: (55, 163, 3), x1=354, x2=517, y1=150, y2=313
Face shape: (11, 137, 3), x1=389, x2=526, y1=80, y2=217
Face shape: (57, 57, 3), x1=908, x2=965, y1=299, y2=356
Face shape: (541, 541, 3), x1=135, x2=676, y1=315, y2=856
Face shape: (49, 188, 3), x1=251, x2=439, y1=47, y2=235
Face shape: (95, 95, 3), x1=95, x2=190, y1=71, y2=166
Face shape: (114, 114, 3), x1=238, x2=352, y1=114, y2=228
Face shape: (457, 457, 3), x1=800, x2=1257, y1=152, y2=609
Face shape: (47, 47, 3), x1=275, x2=322, y1=39, y2=86
Face shape: (191, 191, 3), x1=111, x2=302, y

In [ ]:
print(len(X))
print(len(Y))

904
904


In [ ]:
X = np.array(X)
Y = np.array(Y)

In [ ]:
print(len(X))

904


In [ ]:
if isinstance(X, np.ndarray) and isinstance(Y, np.ndarray):
    print("Images are converted to NumPy arrays.")
else:
    print("Images are not converted to NumPy arrays.")


Images are converted to NumPy arrays.


In [ ]:
#X = X/255.0
X_normalized = X.astype('float32') / 255.0

# Check the shape of the array
print("Shape of X_normalized:", X_normalized.shape)

Shape of X_normalized: (904, 64, 64, 3)


In [ ]:
if np.min(X_normalized) >= 0.0 and np.max(X_normalized) <= 1.0:
    print("Images are properly normalized.")
else:
    print("Images are not properly normalized. Pixel value range: [", np.min(X_normalized), ",", np.max(X_normalized), "]")

Images are properly normalized.


In [ ]:
#reshaping images for oversamlping
X_new = X.reshape(-1, 64*64*3)

In [ ]:
# oversampling the images

from imblearn.over_sampling import SMOTE

sampler = SMOTE()

XSMOTE, YSMOTE = sampler.fit_resample(X_new, Y)

In [ ]:
pd.Series(YSMOTE).value_counts()

6    343
0    343
4    343
3    343
5    343
2    343
1    343
dtype: int64

In [ ]:
# again bringing images to its original shape
X = XSMOTE.reshape(-1, 64, 64, 3)

In [ ]:
#  label encoding, OneHotEncoder
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(Y)
onehot_encoder = OneHotEncoder(sparse=False)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded.reshape(-1, 1))

# Check the shape of onehot_encoded
print("Shape of onehot_encoded:", onehot_encoded.shape)

Shape of onehot_encoded: (904, 7)


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [ ]:
# Check the first few rows of onehot_encoded
print("First few rows of onehot_encoded:")
print(onehot_encoded[:5])

First few rows of onehot_encoded:
[[0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

datagen = ImageDataGenerator(
    rescale = 1.0/255,
    rotation_range = 20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range = 0.2,
    zoom_range = 0.2,
    horizontal_flip = True,
    vertical_flip = True
)

datagen.fit(X)

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from keras.optimizers import Adam
from keras.utils import to_categorical

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_normalized, onehot_encoded, test_size=0.2, random_state=42)

# Build the CNN model
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(64, 64, 3)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(onehot_encoded.shape[1], activation='softmax'))  # Use the number of classes from onehot_encoded

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer=Adam(), metrics=['accuracy'])

# Train the model
batch_size = 32
epochs = 10
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.1)

# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test loss: {loss:.4f}, Test accuracy: {accuracy:.4f}")

Epoch 1/10
21/21 [==============================] - 6s 269ms/step - loss: 1.7477 - accuracy: 0.3046 - val_loss: 1.6243 - val_accuracy: 0.2192
Epoch 2/10
21/21 [==============================] - 4s 205ms/step - loss: 1.6896 - accuracy: 0.3169 - val_loss: 1.6110 - val_accuracy: 0.4795
Epoch 3/10
21/21 [==============================] - 4s 189ms/step - loss: 1.6252 - accuracy: 0.3708 - val_loss: 1.5460 - val_accuracy: 0.2192
Epoch 4/10
21/21 [==============================] - 5s 250ms/step - loss: 1.5825 - accuracy: 0.3754 - val_loss: 1.5162 - val_accuracy: 0.4795
Epoch 5/10
21/21 [==============================] - 4s 205ms/step - loss: 1.5536 - accuracy: 0.3892 - val_loss: 1.4729 - val_accuracy: 0.4521
Epoch 6/10
21/21 [==============================] - 4s 189ms/step - loss: 1.5051 - accuracy: 0.4015 - val_loss: 1.6298 - val_accuracy: 0.2192
Epoch 7/10
21/21 [==============================] - 5s 239ms/step - loss: 1.4208 - accuracy: 0.4462 - val_loss: 1.5178 - val_accuracy: 0.4110
Epoch 